### ISSUE TITLE
passwords can't have spaces

### ISSUE THREAD

**Issue by chadmiller** [yaroto98/ddclient#1]
I can assign a password with spaces in it, but later in the script, it tries to do something with the password variable, and it's unquoted, and so becomes more than one argument.

**Comment by yaroto98** [comment]
Yea, bash can get annoying that way with spaces.

Do you have a password with spaces in it? All the ones I have from Namecheap just look like alphanumeric hashes.

**Comment by chadmiller** [comment]
No, I have none that way, yet.

**Comment by yaroto98** [comment]
Oh ok. Well I'll leave this as an open issue and play around with it some. However, it should really be expanded to any special character bash would choke on.

**Comment by chadmiller** [comment]
Double-quotes around each scalar variable fixes everything, no matter the
characters stored in the variable's value.

**Comment by yaroto98** [comment]
Ah, I see the issue. Fixed with https://github.com/yaroto98/ddclient/commit/48d6f10a3245ca2ea37326810fcd47b7837f5882
