### ISSUE TITLE
address change is too loose

### ISSUE THREAD

**Issue by chadmiller** [yaroto98/ddclient#2]
If my address changes so the resulting address is a substring of the original address, program does not update.

123.45.67.8  -> 123.45.67.89    # no change

**Comment by chadmiller** [comment]
Instead of counting things that grep similarly, just compare string equailty?

``` bash
                diffcheck=`echo $ipaddresscurrent | grep -c $ipaddressnew`
                if [ $diffcheck -eq 0 ];then
                        isdiff=0
                fi
        done
}
```

``` bash
                if test "$ipaddresscurrent" = "$ipaddressnew"; then
                        return 0
                fi
        done
        return 1
}


ipcheck "$domain" $hostlist && update $hostlist "$domain" "$password"
```

**Comment by chadmiller** [comment]
And since the function is a predicate now, it could take a descriptive name like "haschanged"

if haschanged... then; update...; fi

**Comment by yaroto98** [comment]
Issue fixed in commit
https://github.com/yaroto98/ddclient/commit/254e15aa17438f4b7c645ffe5e626eb5941aa0c6
